insert into users(name, surname,username,email,password) values ('Daniel','Marcus','user12','user12@gmail.com','password12')
insert into users(name, surname,username,email,password) values ('Daniel2','Marcus2','user13','user13@gmail.com','password13')
insert into users(name, surname,username,email,password) values ('Daniel3','Marcus3','user14','user14@gmail.com','password14')
insert into users(name, surname,username,email,password) values ('Daniel4','Marcus4','user15','user15@gmail.com','password15')
insert into users(name, surname,username,email,password) values ('Daniel5','Marcus5','user16','user16@gmail.com','password16')